# Generated by Django 4.2.5 on 2023-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentitem',
            name='datetime',
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
