# Generated by Django 4.2.5 on 2023-09-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointmentitem_datetime_appointmentitem_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentitem',
            options={'ordering': ['date', 'time']},
        ),
    ]
