# Generated by Django 4.2.5 on 2023-09-20 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Enter date of birth')),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
                ('town', models.CharField(default='Minsk', help_text='Enter town', max_length=30)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=25, validators=[django.core.validators.RegexValidator(message='Format +375 (29) XXX-XX-XX', regex='^(\\+375 \\(29\\) [0-9]{3}-[0-9]{2}-[0-9]{2})$')])),
            ],
        ),
    ]
