# Generated by Django 4.2.5 on 2023-09-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_news_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='essence',
            field=models.CharField(help_text='Enter essence', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Enter title', max_length=200),
        ),
    ]
