# Generated by Django 4.2.5 on 2023-09-25 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_job', models.CharField(help_text='Enter type of ypor job', max_length=70)),
                ('description', models.TextField(default='', help_text='Enter description')),
                ('is_actual', models.BooleanField(default=False, help_text='Is actual?')),
            ],
        ),
        migrations.CreateModel(
            name='Promotional_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Enter promocode')),
                ('is_actual', models.BooleanField(default=True)),
                ('discount', models.IntegerField(default=10, help_text='Enter discount from 1 to 25', validators=[django.core.validators.MinValueValidator(1, message='The number cannot be less than 1'), django.core.validators.MaxValueValidator(25, message='The number cannot be more than 25')])),
            ],
        ),
    ]
