# Generated by Django 4.2.5 on 2023-09-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Enter type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Enter service name', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('doctor', models.ForeignKey(help_text='Choose a doctor', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('office', models.OneToOneField(help_text='Choose an office', on_delete=django.db.models.deletion.CASCADE, to='services.office')),
                ('service_type', models.ForeignKey(help_text='Choose service type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicetype')),
            ],
        ),
    ]
