# Generated by Django 4.2.5 on 2023-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(help_text='Enter service name', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='designation',
            field=models.CharField(help_text='Enter type', max_length=25),
        ),
    ]
