# Generated by Django 4.2.5 on 2023-09-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_service_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_name']},
        ),
    ]
